POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video batman",
    "description": "video",
    "duration": 280

}


###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/b2da5f3d-641f-4ff4-aa86-d8c4019e582b
Content-Type: application/json


{
    "title": "Video do homem-aranha",
    "description": "Esse é o primeiro video",
    "duration": 180

}


###

DELETE http://localhost:3333/videos/b2da5f3d-641f-4ff4-aa86-d8c4019e582b
